version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    environment:
      DB_PATH: /data/bot.db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
